# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 988188e86b8647baf1e2e18b1395be76e20405db067e53858b79240b99ca98acf908fab5a09794306b47da52be77dddc4a5f62f4169516117c9049fcc26d1a50

test:
  secret_key_base: 5899692ffff19266b3f6b6bba71ef528d5a37911547593c92ac812b428986d3fd47e982711a278a1dfe286a50a8407049d9004ac97248a07f715a70d4e302c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
